[tool.poetry]
name = "wp3-t7"
version = "0.1.0"
description = ""
authors = ["Jose Antonio <joseantoniogarcia@ctnaval.com>",
"Pablo Aguirre <p.aguirre@electronica-submarina.com>",
"Isabel Carozzo <isabel.carozzo@onairweb.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
