[tool.poetry]
name = "pipeline"
version = "0.1.0"
description = ""
authors = ["Jose Antonio Garcia <joseantoniogarcia@ctnaval.com>",
"Isabel Carozzo <isabel.carozzo@onairweb.com>",
"Pablo Aguirre <p.aguirre@electronica-submarina.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.2"
python-dotenv = "^1.0.1"
matplotlib = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
