# Augment mel 
freqm: 0
timem: 0
n_mels: 128
win_length: 800
hopsize: 320
n_fft: 1024
fmin: 0.0
fmax: null
fmin_aug_range: 10
fmax_aug_range: 2000

# Model related
freeze: False

# Hyperparameters
optimizer: adam
lr: 0.001
patience: 4
batch_size: 8
n_epochs: 20

#EcossDataset
sr: 32000
duration: 1

# If we want to test on train set
test_on_train: True