
batch_size : 8
gpu : False

preprocess_type : mel
n_mels : 128
sr : 32000.0
win_length : 800
hopsize : 320
n_fft : 1024
freqm : 5
timem : 19
htk : False
fmin : 0.0
fmax : null
norm : 1
fmin_aug_range : 10
fmax_aug_range : 2000
apply_preemphasis_coefficient : True
duration : 1.0


# Model Parameters
in_channels : 1
model_architecture : passt_s_kd_p16_128_ap486 #passt_l_kd_p16_128_ap47
fstride : 10
tstride : 10
input_fdim : 128
input_tdim : 998
u_patchout : 0
s_patchout_t : 0
s_patchout_f : 0
pretrained : True
weights_path : ""

#hyperparameters
optimizer: "Adam"
lr0: 1.0e-6  # initial learning rate (SGD=1E-2, Adam=1E-3)
momentum: 10  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
scheduler: ""
lrf: 0.001  # final OneCycleLR learning rate (lr0 * lrf)
warmup_epochs: 5.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
patience : 5 # number of epochs without improving loss before early stopping
freeze_layers : False
preanalysis : False
num_epochs : 1