{
 model_path: "/home/isabel/Workspace/ECOSS/WP3_T7/runs/vggish/train/Exp_02/model.joblib",
 labels_mapping_path: "/home/isabel/Workspace/ECOSS/WP3_T7/runs/vggish/train/Exp_02/labels_mapping.json",
 desired_sr: 32000,
 desired_duration: 1
}